apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-desafiofuncional
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-desafiofuncional
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60