- hosts: funcional
  become: true

  tasks:
    - name: Criar diretorio se ele não existir
      ansible.builtin.file:
        path: /opt/funcional
        state: directory
        mode: '0755'

    - name: Criar um filesystem xfs em /dev/xvdb
      community.general.filesystem:
        fstype: xfs
        dev: /dev/xvdb
        
    - name: Montar disco no /opt/funcional
      mount:
        backup: yes #backup do fstab
        path: "/opt/funcional"
        src: /dev/xvdb
        opts: defaults,nofail
        state: mounted
        fstype: xfs

    - name: Instalação de repositorio do NGINX 
      yum:
        update_cache: yes
        pkg:
        - epel-release
        
    - name: Instalação de pacotes necessários 
      yum:
        update_cache: yes
        pkg:
        - nginx
        - zip
        - htop  
        - java-1.8.0-openjdk
        - unzip
  
    - name: Download awscliv2 installer.
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: "{{ executable_temp_dir | default('/tmp') }}"
        remote_src: yes
        creates: /tmp/aws
        mode: 0755

    - name: Run the installer.
      command:
      args:
        cmd: "{{ executable_temp_dir | default('/tmp') }}/aws/install"
        creates: /usr/local/bin/aws
      become: true
      register: aws_install

    - name: Inserindo Página Index.html
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html

    - name: Garante que o nginx inicie ao reiniciar
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Mudar a timezone para America/Sao_Paulo
      community.general.timezone:
        name: America/Sao_Paulo